name: test
on:
- pull_request
jobs:
  xenial-5-2:
    container:
      image: vapor/swift:5.6-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery
  bionic-5-2:
    container:
      image: vapor/swift:5.6-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery
  thread:
    container:
      image: vapor/swift:5.6-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery  --sanitize=thread
  address:
    container:
      image: vapor/swift:5.6-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ASAN_OPTIONS=detect_leaks=0 swift test --enable-test-discovery --sanitize=address
